version: '3'
services:
  bpm-connector1:
    build: .
    image: docker.quancy.com.sg/bpm-connector:${VERSION-latest}
    container_name: bpm1
    network_mode: bridge
    restart: always
    env_file:
      - .env

  bpm-connector2:
    build: .
    image: docker.quancy.com.sg/bpm-connector:${VERSION-latest}
    container_name: bpm2
    network_mode: bridge
    restart: always
    env_file:
      - .env